name: MinigameCore
main: superkael.minigame.core.MinigameCore
version: 1.2.2
commands:
  minigame:
    description: Base command for the Minigame Plugin.
    usage: "Usage: /minigame <mode> [args]"
    aliases: [mg]
    permission: minigame.cmd
permissions:
  minigame.cmd:
    default: op
    description: Allows usage of /minigame